version: '3'

services:
  postgres:
    image: postgres
    container_name: db-postgres-container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    restart: always
    networks:
      - nodeapp

  app:
    build: .
    container_name: node-upload-container
    entrypoint: sh -c "dockerize -wait tcp://postgres:5432 -timeout 30s npm run start:dev"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    ports:
      - 3333:3333
    networks:
      - nodeapp
    depends_on:
      - postgres

networks:
  nodeapp:
    driver: bridge
