version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: api-container
    restart: always
    command: bash -c "npm install && npm run start"
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333
    depends_on:
      - postgres