
app: app-serverless
service: app-serverless
stage: dev

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  funcDir: src/main/functions

functions:
  createBook:
    handler: ${self:custom.funcDir}/book/create-book-function.run
    events:
      - http:
          path: /books
          method: POST

  findAllBook:
    handler: ${self:custom.funcDir}/book/find-all-book-function.run
    events:
      - http:
          path: /books
          method: GET
